Repository mauriciovigolo/keycloak-angular, pull requests merged in 2023-05, with the labels that each got.

#457 Example: add missing `ngOnit`
  projects/example/src/app/app.component.ts
Labels: bug

#455 Add CodeQL workflow
  .github/workflows/codeql.yml
Labels: enhancement

#453 README.md use `Array.isArray()` instead of `instanceof`
  README.md
Labels: documentation

#484 README.md: fix badges
  README.md
Labels: documentation

#459 Enforce LF
  .editorconfig
  .gitattributes
Labels: enhancement

#494 README.md: fix lint and tweak snippets
  README.md
Labels: documentation

#481 feature: support keycloak-js v21.1.0-1
  README.md
  package-lock.json
  package.json
  projects/keycloak-angular/package.json
Labels: dependencies

#495 Support keycloak-js v21.1.1
  README.md
  angular.json
  package-lock.json
  package.json
  projects/example/docker-compose.yml
  projects/example/keycloak-angular-sandbox-users-0.json
  projects/keycloak-angular/package.json
Labels: enhancement, dependencies

#496 Add support to Angular 16
  README.md
  package-lock.json
  package.json
  projects/keycloak-angular/package.json
Labels: enhancement, dependencies
